# Bootcamp Data Science y MLOps

<img src="https://i.ibb.co/5RM26Cw/LOGO-COLOR2.png" width="500px">

---

## Data Preparation

In [1]:
import numpy as np
import pandas as pd

import funpymodeling

In [2]:
# Para este caso nos interesa visualizar todas las columnas
pd.set_option('display.max_columns', None)

In [3]:
# Cargamos el training dataset

df_data_train = pd.read_csv("data/train.csv", sep=',', index_col=0)

In [4]:
print(df_data_train.columns)
print(df_data_train.shape)

Index(['id', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')
(103904, 24)


In [5]:
df_data_train

id  Gender      Customer Type  Age   Type of Travel     Class  \
0        70172    Male     Loyal Customer   13  Personal Travel  Eco Plus   
1         5047    Male  disloyal Customer   25  Business travel  Business   
2       110028  Female     Loyal Customer   26  Business travel  Business   
3        24026  Female     Loyal Customer   25  Business travel  Business   
4       119299    Male     Loyal Customer   61  Business travel  Business   
...        ...     ...                ...  ...              ...       ...   
103899   94171  Female  disloyal Customer   23  Business travel       Eco   
103900   73097    Male     Loyal Customer   49  Business travel  Business   
103901   68825    Male  disloyal Customer   30  Business travel  Business   
103902   54173  Female  disloyal Customer   22  Business travel       Eco   
103903   62567    Male     Loyal Customer   27  Business travel  Business   

        Flight Distance  Inflight wifi service  \
0                   460                      3   
1                   235                      3   
2                  1142                      2   
3                   562                      2   
4                   214                      3   
...                 ...                    ...   
103899              192                      2   
103900             2347                      4   
103901             1995                      1   
103902             1000                      1   
103903             1723                      1   

        Departure/Arrival time convenient  Ease of Online booking  \
0                                       4                       3   
1                                       2                       3   
2                                       2                       2   
3                                       5                       5   
4                                       3                       3   
...                                   ...                     ...   
103899                                  1                       2   
103900                                  4                       4   
103901                                  1                       1   
103902                                  1                       1   
103903                                  3                       3   

        Gate location  Food and drink  Online boarding  Seat comfort  \
0                   1               5                3             5   
1                   3               1                3             1   
2                   2               5                5             5   
3                   5               2                2             2   
4                   3               4                5             5   
...               ...             ...              ...           ...   
103899              3               2                2             2   
103900              4               2                4             5   
103901              3               4                1             5   
103902              5               1                1             1   
103903              3               1                1             1   

        Inflight entertainment  On-board service  Leg room service  \
0                            5                 4                 3   
1                            1                 1                 5   
2                            5                 4                 3   
3                            2                 2                 5   
4                            3                 3                 4   
...                        ...               ...               ...   
103899                       2                 3                 1   
103900                       5                 5                 5   
103901                       4                 3                 2   
103902                       1                 4                 5   
103903                

In [6]:
# Cargamos el test dataset

df_data_test = pd.read_csv("data/test.csv", sep=',', index_col=0)

In [7]:
print(df_data_test.columns)
print(df_data_test.shape)

Index(['id', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')
(25976, 24)


In [8]:
df_data_test

id  Gender      Customer Type  Age   Type of Travel     Class  \
0      19556  Female     Loyal Customer   52  Business travel       Eco   
1      90035  Female     Loyal Customer   36  Business travel  Business   
2      12360    Male  disloyal Customer   20  Business travel       Eco   
3      77959    Male     Loyal Customer   44  Business travel  Business   
4      36875  Female     Loyal Customer   49  Business travel       Eco   
...      ...     ...                ...  ...              ...       ...   
25971  78463    Male  disloyal Customer   34  Business travel  Business   
25972  71167    Male     Loyal Customer   23  Business travel  Business   
25973  37675  Female     Loyal Customer   17  Personal Travel       Eco   
25974  90086    Male     Loyal Customer   14  Business travel  Business   
25975  34799  Female     Loyal Customer   42  Personal Travel       Eco   

       Flight Distance  Inflight wifi service  \
0                  160                      5   
1                 2863                      1   
2                  192                      2   
3                 3377                      0   
4                 1182                      2   
...                ...                    ...   
25971              526                      3   
25972              646                      4   
25973              828                      2   
25974             1127                      3   
25975              264                      2   

       Departure/Arrival time convenient  Ease of Online booking  \
0                                      4                       3   
1                                      1                       3   
2                                      0                       2   
3                                      0                       0   
4                                      3                       4   
...                                  ...                     ...   
25971                                  3                       3   
25972                                  4                       4   
25973                                  5                       1   
25974                                  3                       3   
25975                                  5                       2   

       Gate location  Food and drink  Online boarding  Seat comfort  \
0                  4               3                4             3   
1                  1               5                4             5   
2                  4               2                2             2   
3                  2               3                4             4   
4                  3               4                1             2   
...              ...             ...              ...           ...   
25971              1               4                3             4   
25972              4               4                4             4   
25973              5               2                1             2   
25974              3               4                4             4   
25975              5               4                2             2   

       Inflight entertainment  On-board service  Leg room service  \
0                           5                 5                 5   
1                           4                 4                 4   
2                           2                 4                 1   
3                           1                 1                 1   
4                           2                 2                 2   
...                       ...               ...               ...   
25971                       4                 3                 2   
25972                       4                 4                 5   
25973                       2                 4                 3   
25974                       4                 3                 2   
25975                       1                 1                 2   

       Baggage handli

In [9]:
# Joineamos el training dataset y test dataset

df_data = pd.concat([df_data_train, df_data_test], axis=0)

In [10]:
print(df_data.columns)
print(df_data.shape)

Index(['id', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')
(129880, 24)


In [11]:
df_data

id  Gender      Customer Type  Age   Type of Travel     Class  \
0       70172    Male     Loyal Customer   13  Personal Travel  Eco Plus   
1        5047    Male  disloyal Customer   25  Business travel  Business   
2      110028  Female     Loyal Customer   26  Business travel  Business   
3       24026  Female     Loyal Customer   25  Business travel  Business   
4      119299    Male     Loyal Customer   61  Business travel  Business   
...       ...     ...                ...  ...              ...       ...   
25971   78463    Male  disloyal Customer   34  Business travel  Business   
25972   71167    Male     Loyal Customer   23  Business travel  Business   
25973   37675  Female     Loyal Customer   17  Personal Travel       Eco   
25974   90086    Male     Loyal Customer   14  Business travel  Business   
25975   34799  Female     Loyal Customer   42  Personal Travel       Eco   

       Flight Distance  Inflight wifi service  \
0                  460                      3   
1                  235                      3   
2                 1142                      2   
3                  562                      2   
4                  214                      3   
...                ...                    ...   
25971              526                      3   
25972              646                      4   
25973              828                      2   
25974             1127                      3   
25975              264                      2   

       Departure/Arrival time convenient  Ease of Online booking  \
0                                      4                       3   
1                                      2                       3   
2                                      2                       2   
3                                      5                       5   
4                                      3                       3   
...                                  ...                     ...   
25971                                  3                       3   
25972                                  4                       4   
25973                                  5                       1   
25974                                  3                       3   
25975                                  5                       2   

       Gate location  Food and drink  Online boarding  Seat comfort  \
0                  1               5                3             5   
1                  3               1                3             1   
2                  2               5                5             5   
3                  5               2                2             2   
4                  3               4                5             5   
...              ...             ...              ...           ...   
25971              1               4                3             4   
25972              4               4                4             4   
25973              5               2                1             2   
25974              3               4                4             4   
25975              5               4                2             2   

       Inflight entertainment  On-board service  Leg room service  \
0                           5                 4                 3   
1                           1                 1                 5   
2                           5                 4                 3   
3                           2                 2                 5   
4                           3                 3                 4   
...                       ...               ...               ...   
25971                       4                 3                 2   
25972                       4                 4                 5   
25973                       2                 4                 3   
25974                       4                 3                 2   
25975                       1                 1                 2   

       Bag

In [12]:
# Seleccionamos algunas columnas del dataset

columns = [
    'Age', 'Class', 'Inflight wifi service',
    'Ease of Online booking', 'Seat comfort',
    'Checkin service', 'satisfaction',
]

df_data = df_data[columns].copy()

In [13]:
# Renombramos algunas columnas

df_data.rename(
    columns = {
        'Inflight wifi service': 'Wifi',
        'Ease of Online booking': 'Booking',
        'Seat comfort': 'Seat',
        'Checkin service': 'Checkin',
    }, 
    inplace=True
)

In [14]:
# Transformamos la columna "satisfaction"

class_map = {'neutral or dissatisfied': 0, 'satisfied': 1}
df_data['satisfaction'] = df_data['satisfaction'].map(class_map)

In [15]:
df_data

Age     Class  Wifi  Booking  Seat  Checkin  satisfaction
0       13  Eco Plus     3        3     5        4             0
1       25  Business     3        3     1        1             0
2       26  Business     2        2     5        4             1
3       25  Business     2        5     2        1             0
4       61  Business     3        3     5        3             1
...    ...       ...   ...      ...   ...      ...           ...
25971   34  Business     3        3     4        4             0
25972   23  Business     4        4     4        5             1
25973   17       Eco     2        1     2        5             0
25974   14  Business     3        3     4        4             1
25975   42       Eco     2        2     2        1             0

[129880 rows x 7 columns]

In [16]:
# Aplicamos Get Dummies sobre el Dataset

df_data_dummies = pd.get_dummies(df_data) 

In [17]:
df_data_dummies

Age  Wifi  Booking  Seat  Checkin  satisfaction  Class_Business  \
0       13     3        3     5        4             0               0   
1       25     3        3     1        1             0               1   
2       26     2        2     5        4             1               1   
3       25     2        5     2        1             0               1   
4       61     3        3     5        3             1               1   
...    ...   ...      ...   ...      ...           ...             ...   
25971   34     3        3     4        4             0               1   
25972   23     4        4     4        5             1               1   
25973   17     2        1     2        5             0               0   
25974   14     3        3     4        4             1               1   
25975   42     2        2     2        1             0               0   

       Class_Eco  Class_Eco Plus  
0              0               1  
1              0               0  
2              0               0  
3              0               0  
4              0               0  
...          ...             ...  
25971          0               0  
25972          0               0  
25973          1               0  
25974          0               0  
25975          1               0  

[129880 rows x 9 columns]

In [33]:
funpymodeling.status(df_data_dummies)

variable  q_nan  p_nan  q_zeros   p_zeros  unique   type
0             Age      0    0.0        0  0.000000      75  int64
1            Wifi      0    0.0     3916  0.030151       6  int64
2         Booking      0    0.0     5682  0.043748       6  int64
3            Seat      0    0.0        1  0.000008       6  int64
4         Checkin      0    0.0        1  0.000008       6  int64
5    satisfaction      0    0.0    73452  0.565537       2  int64
6  Class_Business      0    0.0    67720  0.521404       2  uint8
7       Class_Eco      0    0.0    71571  0.551055       2  uint8
8  Class_Eco Plus      0    0.0   120469  0.927541       2  uint8

In [37]:
df_data_dummies.describe().T

count       mean        std  min   25%   50%   75%   max
Age             129880.0  39.427957  15.119360  7.0  27.0  40.0  51.0  85.0
Wifi            129880.0   2.728696   1.329340  0.0   2.0   3.0   4.0   5.0
Booking         129880.0   2.756876   1.401740  0.0   2.0   3.0   4.0   5.0
Seat            129880.0   3.441361   1.319289  0.0   2.0   4.0   5.0   5.0
Checkin         129880.0   3.306267   1.266185  0.0   3.0   3.0   4.0   5.0
satisfaction    129880.0   0.434463   0.495688  0.0   0.0   0.0   1.0   1.0
Class_Business  129880.0   0.478596   0.499544  0.0   0.0   0.0   1.0   1.0
Class_Eco       129880.0   0.448945   0.497388  0.0   0.0   0.0   1.0   1.0
Class_Eco Plus  129880.0   0.072459   0.259248  0.0   0.0   0.0   0.0   1.0

In [39]:
df_data_dummies['Wifi'].unique()

array([3, 2, 4, 1, 5, 0])

In [41]:
df_data_dummies['Booking'].unique()

array([3, 2, 5, 4, 1, 0])

In [44]:
df_data_dummies['Seat'].unique()

array([5, 1, 2, 3, 4, 0])

In [45]:
df_data_dummies['Checkin'].unique()

array([4, 1, 3, 5, 2, 0])

## Separación de X de Y para entrenamiento

In [18]:
data_x = df_data_dummies.drop('satisfaction', axis=1)
data_y = df_data_dummies['satisfaction']

In [19]:
# Guardamos las columnas

import pickle

with open('pickle_files/categories_ohe.pkl', 'wb') as f:
    pickle.dump(data_x.columns, f, protocol=pickle.HIGHEST_PROTOCOL)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
# Spliteamos el dataset
x_train, x_test, y_train, y_test = train_test_split(
    data_x, data_y, test_size=0.3,
)

In [22]:
x_train

Age  Wifi  Booking  Seat  Checkin  Class_Business  Class_Eco  \
53544    31     4        4     3        2               0          1   
795      56     2        2     4        4               1          0   
41656    27     4        4     5        1               1          0   
70730    27     2        2     3        2               1          0   
101176   20     4        5     3        3               0          1   
...     ...   ...      ...   ...      ...             ...        ...   
103374   69     2        2     1        2               0          1   
77001    53     2        2     4        1               0          1   
33830    15     5        5     3        5               1          0   
22324    28     3        3     4        4               0          1   
97729    49     2        1     2        4               0          0   

        Class_Eco Plus  
53544                0  
795                  0  
41656                0  
70730                0  
101176               0  
...                ...  
103374               0  
77001                0  
33830                0  
22324                0  
97729                1  

[90916 rows x 8 columns]

In [23]:
y_train

53544     0
795       1
41656     1
70730     0
101176    1
         ..
103374    0
77001     0
33830     1
22324     0
97729     0
Name: satisfaction, Length: 90916, dtype: int64

## Creacion y entrenamiento del modelo

In [24]:
from sklearn.ensemble import RandomForestClassifier 

In [25]:
# Creamos 1000 decision trees
rf_model = RandomForestClassifier(n_estimators=1000, random_state=19)

In [26]:
%%time

rf_model.fit(x_train, y_train)

CPU times: user 29.6 s, sys: 421 ms, total: 30 s
Wall time: 30.5 s


RandomForestClassifier(n_estimators=1000, random_state=19)

## Calculamos algunas metricas del modelo entrenado

In [27]:
# En training (por defecto asume 0.5 como punto de corte)
pred_tr = rf_model.predict(x_train)

In [47]:
x_train

Age  Wifi  Booking  Seat  Checkin  Class_Business  Class_Eco  \
53544    31     4        4     3        2               0          1   
795      56     2        2     4        4               1          0   
41656    27     4        4     5        1               1          0   
70730    27     2        2     3        2               1          0   
101176   20     4        5     3        3               0          1   
...     ...   ...      ...   ...      ...             ...        ...   
103374   69     2        2     1        2               0          1   
77001    53     2        2     4        1               0          1   
33830    15     5        5     3        5               1          0   
22324    28     3        3     4        4               0          1   
97729    49     2        1     2        4               0          0   

        Class_Eco Plus  
53544                0  
795                  0  
41656                0  
70730                0  
101176               0  
...                ...  
103374               0  
77001                0  
33830                0  
22324                0  
97729                1  

[90916 rows x 8 columns]

In [48]:
pred_tr

array([0, 1, 1, ..., 1, 0, 0])

In [28]:
# En testing (por defecto asume 0.5 como punto de corte)
pred_ts = rf_model.predict(x_test)

In [29]:
from pprint import pprint

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [30]:
train_metrics = {
    'accuracy': accuracy_score(y_train, pred_tr, normalize=True),
    'precision': precision_score(y_train, pred_tr),
    'recall': recall_score(y_train, pred_tr),
    'f1_score': f1_score(y_train, pred_tr),
}

pprint(train_metrics)

{'accuracy': 0.9360948567908839,
 'f1_score': 0.9268759282100334,
 'precision': 0.9197681970325223,
 'recall': 0.9340943683409437}


In [31]:
test_metrics = {
    'accuracy': accuracy_score(y_test, pred_ts, normalize=True),
    'precision': precision_score(y_test, pred_ts),
    'recall': recall_score(y_test, pred_ts),
    'f1_score': f1_score(y_test, pred_ts),
}

pprint(test_metrics)

{'accuracy': 0.8828662354994353,
 'f1_score': 0.8665262911621922,
 'precision': 0.8620388688467358,
 'recall': 0.871060677328316}


# Guardamos el modelo entrenado

In [32]:
# Guardar en el disco
filename = 'model/rf.pkl'
pickle.dump(rf_model, open(filename, 'wb'))